-- ============================================================
-- DROP TABLES (child → parent)
-- ============================================================
DROP TABLE IF EXISTS company_file CASCADE;
DROP TABLE IF EXISTS company_embedding CASCADE;
DROP TABLE IF EXISTS company_bookmark CASCADE;
DROP TABLE IF EXISTS company_following CASCADE;
DROP TABLE IF EXISTS feedback_comment CASCADE;
DROP TABLE IF EXISTS feedback_board CASCADE;
DROP TABLE IF EXISTS user_profile CASCADE;
DROP TABLE IF EXISTS dart_report CASCADE;
DROP TABLE IF EXISTS disclosure_file CASCADE;
DROP TABLE IF EXISTS disclosure_list CASCADE;
DROP TABLE IF EXISTS financial_account CASCADE;
DROP TABLE IF EXISTS financial_index CASCADE;

-- legacy tables to clean out
DROP TABLE IF EXISTS company CASCADE;
DROP TABLE IF EXISTS user_account CASCADE;


-- ============================================================
-- CREATE TABLES (base tables first, then dependents)
-- ============================================================

-- 사용자 계정
CREATE TABLE user_account (
    user_account_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR(255) NOT NULL UNIQUE,
    password        VARCHAR(255) NOT NULL,
    role_name       VARCHAR(255) NOT NULL CHECK (role_name IN ('USER','ADMIN')),
    status          VARCHAR(255) NOT NULL CHECK (status IN ('ACTIVE','WITHDRAWN','BANNED')),
    created_at      TIMESTAMP(6),
    updated_at      TIMESTAMP(6)
);

-- 회사 기본 정보
CREATE TABLE company (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    corp_code           VARCHAR(255),
    name                VARCHAR(255),
    stock_code          VARCHAR(255),
    induty_code         VARCHAR(255),
    market              VARCHAR(255),
    homepage_url        VARCHAR(255),
    headquarters_addr   VARCHAR(255),
    founded_date        TIMESTAMP(6),
    corporate_reg_no    VARCHAR(255),
    business_reg_no     VARCHAR(255),
    phone_number        VARCHAR(255),
    description         TEXT,
    overview            TEXT,
    created_at          TIMESTAMP(6),
    updated_at          TIMESTAMP(6)
);

-- 회사 요약 임베딩 (pgvector 1536 차원; PCA 후 임베딩)
CREATE TABLE company_embedding (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id  BIGINT NOT NULL,
    embedding   VECTOR(1536),
    created_at  TIMESTAMP(6)
);

-- 회사 파일 (유저 업로드 → 실제 회사 귀속)
CREATE TABLE company_file (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT NOT NULL,
    uploaded_by     BIGINT NOT NULL,
    file_type       VARCHAR(255) NOT NULL CHECK (file_type IN ('PDF','TXT','XML','HTML','DOCX','IMAGE')),
    file_url        VARCHAR(1024),
    original_name   VARCHAR(512),
    raw_content     TEXT,
    created_at      TIMESTAMP(6)
);

-- 회사 북마크 (유저 ↔ 회사)
CREATE TABLE company_bookmark (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_account_id  BIGINT NOT NULL,
    company_id       BIGINT NOT NULL,
    created_at       TIMESTAMP(6),
    UNIQUE (user_account_id, company_id)
);

-- 회사 팔로잉 (유저 ↔ 회사)
CREATE TABLE company_following (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_account_id  BIGINT NOT NULL,
    company_id       BIGINT NOT NULL,
    created_at       TIMESTAMP(6),
    UNIQUE (user_account_id, company_id)
);

-- 유저 프로필
CREATE TABLE user_profile (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_account_id  BIGINT UNIQUE,
    username         VARCHAR(255),
    bio              VARCHAR(255),
    profile_image    OID,
    created_at       TIMESTAMP(6),
    updated_at       TIMESTAMP(6)
);

-- 피드백 게시판
CREATE TABLE feedback_board (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_account_id  BIGINT,
    title            VARCHAR(255) NOT NULL,
    content          TEXT NOT NULL,
    is_public        BOOLEAN,
    created_at       TIMESTAMP(6),
    updated_at       TIMESTAMP(6),
    deleted_at       TIMESTAMP(6)
);

-- 피드백 댓글
CREATE TABLE feedback_comment (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feedback_board_id BIGINT,
    user_account_id   BIGINT,
    content           TEXT NOT NULL,
    created_at        TIMESTAMP(6),
    updated_at        TIMESTAMP(6),
    deleted_at        TIMESTAMP(6)
);

-- 공시 리스트
CREATE TABLE disclosure_list (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id  BIGINT NOT NULL,
    rcept_no    VARCHAR(255) NOT NULL UNIQUE,
    flr_nm      VARCHAR(255),
    report_nm   VARCHAR(255),
    rpt_type    VARCHAR(255),
    rcept_dt    DATE,
    created_at  TIMESTAMP(6)
);

-- 공시 파일
CREATE TABLE disclosure_file (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    disclosure_id  BIGINT NOT NULL,
    file_type      VARCHAR(255) CHECK (file_type IN ('HTML','PDF','XBRL')),
    file_url       VARCHAR(255),
    raw_content    TEXT,
    created_at     TIMESTAMP(6),
    CONSTRAINT uq_disclosure_file UNIQUE (disclosure_id, file_type, file_url)
);

-- 정기보고서
CREATE TABLE dart_report (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id  BIGINT,
    rcept_no    VARCHAR(255) UNIQUE,
    report_type VARCHAR(255),
    title       VARCHAR(255),
    content     TEXT,
    published_at TIMESTAMP(6),
    created_at  TIMESTAMP(6)
);

-- 재무 계정
CREATE TABLE financial_account (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id  BIGINT,
    account_id  VARCHAR(255),
    account_nm  VARCHAR(255),
    bsns_year   INTEGER,
    thstrm_amount      BIGINT,
    reprt_code  VARCHAR(255),
    created_at  TIMESTAMP(6)
);

-- 재무 지표
CREATE TABLE financial_index (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id  BIGINT,
    index_nm    VARCHAR(255),
    index_value FLOAT8,
    bsns_year   INTEGER,
    reprt_code  VARCHAR(255),
    created_at  TIMESTAMP(6)
);


-- ============================================================
-- FOREIGN KEYS
-- ============================================================

-- user_account relations
ALTER TABLE user_profile
    ADD CONSTRAINT fk_user_profile_user
        FOREIGN KEY (user_account_id) REFERENCES user_account (user_account_id);

ALTER TABLE feedback_board
    ADD CONSTRAINT fk_feedback_board_user
        FOREIGN KEY (user_account_id) REFERENCES user_account (user_account_id);

ALTER TABLE feedback_comment
    ADD CONSTRAINT fk_feedback_comment_user
        FOREIGN KEY (user_account_id) REFERENCES user_account (user_account_id);

ALTER TABLE company_bookmark
    ADD CONSTRAINT fk_company_bookmark_user
        FOREIGN KEY (user_account_id) REFERENCES user_account (user_account_id);

ALTER TABLE company_following
    ADD CONSTRAINT fk_company_following_user
        FOREIGN KEY (user_account_id) REFERENCES user_account (user_account_id);

ALTER TABLE company_file
    ADD CONSTRAINT fk_company_file_user
        FOREIGN KEY (uploaded_by) REFERENCES user_account (user_account_id);


-- company relations
ALTER TABLE company_embedding
    ADD CONSTRAINT fk_company_embedding_company
        FOREIGN KEY (company_id) REFERENCES company (id);

ALTER TABLE company_file
    ADD CONSTRAINT fk_company_file_company
        FOREIGN KEY (company_id) REFERENCES company (id);


ALTER TABLE company_bookmark
    ADD CONSTRAINT fk_company_bookmark_company
        FOREIGN KEY (company_id) REFERENCES company (id);

ALTER TABLE company_following
    ADD CONSTRAINT fk_company_following_company
        FOREIGN KEY (company_id) REFERENCES company (id);

ALTER TABLE disclosure_list
    ADD CONSTRAINT fk_disclosure_list_company
        FOREIGN KEY (company_id) REFERENCES company (id);

ALTER TABLE dart_report
    ADD CONSTRAINT fk_dart_report_company
        FOREIGN KEY (company_id) REFERENCES company (id);

ALTER TABLE financial_account
    ADD CONSTRAINT fk_financial_account_company
        FOREIGN KEY (company_id) REFERENCES company (id);

ALTER TABLE financial_index
    ADD CONSTRAINT fk_financial_index_company
        FOREIGN KEY (company_id) REFERENCES company (id);

-- disclosure chain
ALTER TABLE disclosure_file
    ADD CONSTRAINT fk_disclosure_file_disclosure
        FOREIGN KEY (disclosure_id) REFERENCES disclosure_list (id);


-- dart report chain

-- feedback chain
ALTER TABLE feedback_comment
    ADD CONSTRAINT fk_feedback_comment_board
        FOREIGN KEY (feedback_board_id) REFERENCES feedback_board (id);


-- ============================================================
-- INDEXES (btree + vector HNSW)
-- ============================================================

-- company-centric lookups
CREATE INDEX idx_company_stock_code ON company (stock_code);
CREATE INDEX idx_company_corp_code ON company (corp_code);

-- user/company relations
CREATE INDEX idx_company_bookmark_user ON company_bookmark (user_account_id);
CREATE INDEX idx_company_following_user ON company_following (user_account_id);
CREATE INDEX idx_company_bookmark_company ON company_bookmark (company_id);
CREATE INDEX idx_company_following_company ON company_following (company_id);

-- feedback
CREATE INDEX idx_feedback_board_user ON feedback_board (user_account_id);
CREATE INDEX idx_feedback_comment_board_user ON feedback_comment (feedback_board_id, user_account_id);

-- disclosure / reports
CREATE INDEX idx_disclosure_list_company_date ON disclosure_list (company_id, rcept_dt DESC);
CREATE INDEX idx_disclosure_file_disclosure ON disclosure_file (disclosure_id);
CREATE INDEX idx_disclosure_file_unique ON disclosure_file (disclosure_id, file_type, file_url);
CREATE INDEX idx_dart_report_company ON dart_report (company_id);

-- financial
CREATE INDEX idx_financial_account_company_year ON financial_account (company_id, bsns_year, account_id);
CREATE INDEX idx_financial_index_company_year ON financial_index (company_id, bsns_year, index_nm);

-- files and embeddings
CREATE INDEX idx_company_file_company ON company_file (company_id);
CREATE INDEX idx_company_file_uploaded_by ON company_file (uploaded_by);
-- vector search (pgvector: cosine distance)
CREATE INDEX idx_company_embedding_hnsw ON company_embedding USING hnsw (embedding vector_cosine_ops);
